-- One row per person who signed up, with the attributes the dashboard filters on.
CREATE TABLE IF NOT EXISTS users (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    signed_up_at TIMESTAMPTZ NOT NULL,
    channel      TEXT NOT NULL CHECK (channel IN ('invite', 'search', 'social', 'direct')),
    platform     TEXT NOT NULL CHECK (platform IN ('ios', 'android', 'web'))
);

-- Append-only log of what users did. Every metric is derived from this table.
CREATE TABLE IF NOT EXISTS events (
    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    name        TEXT NOT NULL CHECK (name IN (
                    'signed_up', 'profile_completed', 'group_joined',
                    'session_started', 'session_completed')),
    occurred_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS users_signed_up_at_idx ON users (signed_up_at);
-- Per-user lookups: "first time this user did X" and "was this user active in week N".
CREATE INDEX IF NOT EXISTS events_user_name_time_idx ON events (user_id, name, occurred_at);
-- Finding the latest event, which sets the "data through" date.
CREATE INDEX IF NOT EXISTS events_occurred_at_idx ON events (occurred_at);
